Andre Luckow's suggestions 1 & 2 implemented
1. On https://becksteinlab.github.io/SPIDAL-MDAnalysis-Midas-tutorial/installation.html:
source activate mdaenv is mentioned twice. Not needed before RP
installation again.

2. Session already exists error when run multiple times... we probably
should mention that the last parameter is the session name that can be
adjusted or we automatically create one using a UUID:
database   : [mongodb://login1.wrangler.tacc.utexas.edu/radicalpilot]        err
2017-02-06 20:19:06,556: radical.pilot       : MainProcess
       : MainThread     : ERROR   : session create failed
Traceback (most recent call last):
 File "/home/01131/tg804093/miniconda2/envs/mdaenv/lib/python2.7/site-packages/radical/pilot/session.py",
line 154, in __init__
   dburl = dburl)
 File "/home/01131/tg804093/miniconda2/envs/mdaenv/lib/python2.7/site-packages/radical/pilot/db/database.py",
line 69, in __init__
   raise RuntimeError("Session '%s' already exists." % sid)
RuntimeError: Session 'spidal_mda_rp_psa' already exists.
caught Exception: Couldn't create new session (database URL
'mongodb://login1.wrangler.tacc.utexas.edu/radicalpilot' incorrect?):
Session 'spidal_mda_rp_psa' already exists.

3. Using Resource xsede.wrangler: This is probably caused by the two
factor authentication required by TACC resources. We might want to use
a different resource or utilize a way to directly submit to SLURM
without SSH (did not see it in the resource list:
http://radicalpilot.readthedocs.io/en/latest/_downloads/resource_xsede.json
though)

Could not detect shell prompt (timeout)
(/home/01131/tg804093/miniconda2/envs/mdaenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py
+290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell
prompt (timeout)"))
Traceback (most recent call last):
 File "/home/01131/tg804093/miniconda2/envs/mdaenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py",
line 290, in _initialize_pty
   raise se.NoSuccess ("Could not detect shell prompt (timeout)")
NoSuccess: Could not detect shell prompt (timeout)
(/home/01131/tg804093/miniconda2/envs/mdaenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py
+290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell
prompt (timeout)"))
caught Exception: Could not detect shell prompt (timeout)
(/home/01131/tg804093/miniconda2/envs/mdaenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py
+290 (_initialize_pty)  :  raise se.NoSuccess ("Could not detect shell
prompt (timeout)"))
Closing session, exiting now ...

4. We should also make it work for "local.localhost"! But this
requires some complex if/else when creating the Pilot Description as
local.localhost fails when a project id is set (not sure why... but I
guess this is due to AndreM's love for strong typing).